# MicroTosca types

# MicroTOSCA node types
MICROTOSCA_NODES_SERVICE = 'micro.nodes.Service'
MICROTOSCA_NODES_DATABASE = 'micro.nodes.Datastore'

MICROTOSCA_NODES_COMMUNICATIONPATTERN = 'micro.nodes.CommunicationPattern'
MICROTOSCA_NODES_MESSAGE_BROKER = 'micro.nodes.MessageBroker'
MICROTOSCA_NODES_MESSAGE_ROUTER = 'micro.nodes.MessageRouter'

MICROTOSCA_NODES_MESSAGE_ROUTER_KINGRESS = 'micro.nodes.MessageRouter.KIngress'
MICROTOSCA_NODES_MESSAGE_ROUTER_KSERVICE = 'micro.nodes.MessageRouter.KService'
MICROTOSCA_NODES_MESSAGE_ROUTER_KPROXY = 'micro.nodes.MessageRouter.KProxy'

# MicroTOSCA relationship types
MICROTOSCA_RELATIONSHIPS_INTERACT_WITH = 'micro.relationships.InteractsWith'
MICROTOSCA_RELATIONSHIPS_INTERACT_WITH_TIMEOUT_PROPERTY = "timeout"
MICROTOSCA_RELATIONSHIPS_INTERACT_WITH_CIRCUIT_BREAKER_PROPERTY = "circuit_breaker"
MICROTOSCA_RELATIONSHIPS_INTERACT_WITH_DYNAMIC_DISCOVEY_PROPERTY = "dynamic_discovery"

# MicroTOSCA group types
MICROTOSCA_GROUPS_TEAM = 'micro.groups.Team'
MICROTOSCA_GROUPS_EDGE = 'micro.groups.Edge'
