# Relationship instance name

YML_RUN_TIME = "run_time"
YML_DEPLOYMENT_TIME = "deployment_time"


YML_RELATIONSHIP_TEMPLATE = YML_RELATIONSHIP_T, YML_RELATIONSHIP_C, YML_RELATIONSHIP_D, YML_RELATIONSHIP_TC, YML_RELATIONSHIP_TD, YML_RELATIONSHIP_CD, YML_RELATIONSHIP_TCD =\
               't', 'c', 'd', 'tc', 'td', 'cd', 'tcd'